# Generated by Django 3.2 on 2023-01-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_building_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='create_user',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='update_user',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
