# Generated by Django 3.2 on 2023-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
