# Generated by Django 4.1.5 on 2023-01-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230119_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonworkingdays',
            name='project_id',
        ),
        migrations.AddField(
            model_name='nonworkingdays',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.project'),
        ),
    ]
