# Generated by Django 3.2 on 2023-01-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230119_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_by_user', to='core.user'),
        ),
        migrations.AlterField(
            model_name='building',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_by_user', to='core.user'),
        ),
    ]
