# Generated by Django 3.2 on 2023-01-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230119_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization'),
        ),
    ]
