# Generated by Django 3.2 on 2023-01-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_building_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='organization_id',
        ),
    ]
