# Generated by Django 3.2 on 2023-01-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_building_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization'),
        ),
    ]
