# Generated by Django 3.2 on 2023-01-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230119_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingitem',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='buildingitem',
            name='building_id',
        ),
        migrations.RemoveField(
            model_name='buildingitem',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='buildingitem',
            name='people_id',
        ),
        migrations.RemoveField(
            model_name='buildingitem',
            name='update_user',
        ),
        migrations.AddField(
            model_name='buildingitem',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.building'),
        ),
        migrations.AddField(
            model_name='buildingitem',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.people'),
        ),
        migrations.AlterField(
            model_name='view',
            name='enable_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='buildingitem',
            table='core_building_item',
        ),
    ]
