# Generated by Django 3.2 on 2023-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230119_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
