# Generated by Django 3.2 on 2023-01-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_people_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingitem',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='building_item_created_by', to='core.user'),
        ),
        migrations.AddField(
            model_name='buildingitem',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='building_item_updated_by', to='core.user'),
        ),
    ]
